import { describe, expect, test } from "bun:test"
import { readFileSync } from "node:fs"

describe("desktop deep-research real-path verifier script", () => {
  test("exposes the desktop:verify:deep-research script and guards the real Deep Research path", () => {
    const packageJson = JSON.parse(readFileSync("package.json", "utf8")) as {
      scripts?: Record<string, string>
    }
    const scriptSource = readFileSync("scripts/desktop-deep-research-verify.mjs", "utf8")

    expect(packageJson.scripts?.["desktop:verify:deep-research"]).toBe(
      "node ./scripts/desktop-deep-research-verify.mjs",
    )

    expect(scriptSource).toContain("import { _electron as electron } from \"playwright\"")
    expect(scriptSource).toContain("DESKTOP_DEEP_RESEARCH_VERIFY_PROMPT")
    expect(scriptSource).toContain("current-env")
    expect(scriptSource).toContain("task-7-deep-research-real-path")
    expect(scriptSource).toContain("trace.zip")
    expect(scriptSource).toContain("screenshot.png")
    expect(scriptSource).toContain("session-summary.json")
    expect(scriptSource).toContain("lifecycle-summary.json")
    expect(scriptSource).toContain("timeline-summary.json")
    expect(scriptSource).toContain("sqlite-telemetry-summary.json")
    expect(scriptSource).toContain("writeEvidenceSummaries")
    expect(scriptSource.indexOf("writeEvidenceSummaries({")).toBeLessThan(
      scriptSource.indexOf("assertSubagentUsage({ lifecycleSummary, timelineSummary, sqliteTelemetry })"),
    )
    expect(scriptSource).toContain("SUMMARY_PREVIEW_LIMIT = 500")
    expect(scriptSource).toContain("SUBAGENT_RESULT_SIZE_LIMIT = 50_000")
    expect(scriptSource).toContain("WEBFETCH_TRUNCATED_RESULT_MAX = 55_000")
    expect(scriptSource).toContain("https://raw.githubusercontent.com/microsoft/TypeScript/main/src/compiler/checker.ts")

    expect(scriptSource).toContain("DESKTOP_WORKSPACE_ROOT")
    expect(scriptSource).toContain("DESKTOP_SELECTION_STATE_PATH")
    expect(scriptSource).toContain("DESKTOP_SETTINGS_STATE_PATH")
    expect(scriptSource).toContain("NCOWORKER_SERVER_DB_PATH")
    expect(scriptSource).toContain("window.neoCoworkerDesktop.requestJson")
    expect(scriptSource).toContain("window.neoCoworkerDesktop.persistedWorkspaceRoot")
    expect(scriptSource).toContain("window.neoCoworkerDesktop.loadDesktopSettings")
    expect(scriptSource).toContain("page.context().tracing.start")
    expect(scriptSource).toContain("page.context().tracing.stop")

    expect(scriptSource).toContain("/agents/primary")
    expect(scriptSource).toContain("assertPrimaryAgentDisplayNames")
    expect(scriptSource).toContain("General")
    expect(scriptSource).toContain("Plan")
    expect(scriptSource).toContain("Deep Research")
    expect(scriptSource).toContain("source-researcher")
    expect(scriptSource).toContain("Source Researcher")
    expect(scriptSource).toContain("data-testid=\"agent-badge\"")
    expect(scriptSource).toContain("data-testid=\"agent-option-deep-research\"")
    expect(scriptSource).toContain("page.locator(\"textarea\")")
    expect(scriptSource).toContain("button[type=submit]")

    expect(scriptSource).toContain("readSqliteTelemetrySummary")
    expect(scriptSource).toContain("DatabaseSync")
    expect(scriptSource).toContain("FROM session")
    expect(scriptSource).toContain("FROM run_event")
    expect(scriptSource).toContain("FROM message")
    expect(scriptSource).toContain("FROM part")
    expect(scriptSource).toContain("parent_session_id")
    expect(scriptSource).toContain("tool.call.requested")
    expect(scriptSource).toContain("tool.call.completed")
    expect(scriptSource).toContain("skill.load.completed")
    expect(scriptSource).toContain("skill.load.failed")
    expect(scriptSource).toContain("subagent.started")
    expect(scriptSource).toContain("subagent.completed")
    expect(scriptSource).toContain("Number.isInteger(event.maxTurns)")
    expect(scriptSource).toContain("event.maxTurns <= 0")
    expect(scriptSource).toContain("invalid source-researcher maxTurns telemetry")
    expect(scriptSource).toContain("assertNoUnknownWebsearchError")
    expect(scriptSource).toContain("Unknown tool: websearch")
    expect(scriptSource).toContain("assertSourceResearcherWebsearchAvailable")
    expect(scriptSource).toContain('part.toolName === "websearch"')

    expect(scriptSource).toContain("summarizeEventData")
    expect(scriptSource).toContain("summarizeToolPart")
    expect(scriptSource).toContain("outputLength: output.length")
    expect(scriptSource).toContain("outputPreview: preview(output)")
    expect(scriptSource).toContain("appendSafeToolInputFields")
    expect(scriptSource).toContain("isSensitiveTextKey")
    expect(scriptSource).toContain("lengthKeyForSensitiveText")
    expect(scriptSource).toContain("sanitizeMetadata")
    expect(scriptSource).toContain("summarizeSessionRecord")
    expect(scriptSource).toContain("fullPromptLength")
    expect(scriptSource).toContain("promptLength")
    expect(scriptSource).toContain("inputLength")
    expect(scriptSource).toContain("result.metadata?.truncated === true")
    expect(scriptSource).toContain("typeof result.metadata?.savedPath === \"string\"")
    expect(scriptSource).toContain("assertToolResultStorageAndTelemetry")
    expect(scriptSource).toContain("assertReasoningReplayTelemetry")
    expect(scriptSource).toContain("assertNoLiteralThinkTagLeak")
    expect(scriptSource).toContain("literalThinkTagCount")
    expect(scriptSource).toContain("countLiteralThinkTags")
    expect(scriptSource).toContain("childRunIds.has(event.runId)")
    expect(scriptSource).toContain("SQLite telemetry did not identify a source-researcher child session.")
    expect(scriptSource).toContain("Real Task 7 path did not record any managed child/source-researcher tool result with metadata.savedPath.")
    expect(scriptSource).toContain("Managed child tool result did not include expected 50KB truncation metadata.")
    expect(scriptSource).toContain("Real Task 7 path did not record child budget.result_truncated or budget.spill_largest telemetry.")
    expect(scriptSource).toContain("budget.result_truncated")
    expect(scriptSource).toContain("budget.spill_largest")
    expect(scriptSource).toContain("sourceResearcherChildSessionIds")
    expect(scriptSource).toContain("sourceResearcherChildRunIds.has(event.runId)")
    expect(scriptSource).toContain(".ncoworker/tool-results/${result.sessionId}/${result.toolName}/")
    expect(scriptSource).toContain("existsSync(join(input.workspaceRoot, result.metadata.savedPath))")

    expect(scriptSource).toContain("assertNoWorkspaceSkillFallback")
    expect(scriptSource).toContain(".ncoworker")
    expect(scriptSource).toContain("skills")
    expect(scriptSource).toContain("research")
    expect(scriptSource).toContain("source-note")
    expect(scriptSource).toContain("SKILL.md")
    expect(scriptSource).toContain("research/source-note")
    expect(scriptSource).toContain("ENOENT")
    expect(scriptSource).toContain(".ncoworker/skills/research/deep-research/references/*.md")
    expect(scriptSource).toContain("references/source-note-schema.md")
    expect(scriptSource).toContain("webfetch builtin:research/source-note/SKILL.md")
    expect(scriptSource).toContain("assertBuiltinReferenceReadPaths")
    expect(scriptSource).toContain("/builtin-skills/")
    expect(scriptSource).toContain("/references/source-note-schema.md")
    expect(scriptSource).toContain("reasonable final output")
    expect(scriptSource).toContain('"create_skill"')
    expect(scriptSource).toContain('"patch_skill"')
    expect(scriptSource).toContain('"delete_skill"')
    expect(scriptSource).toContain("calledToolNames.has(operation) === false")

    expect(scriptSource).not.toContain("startMockModelServer")
    expect(scriptSource).not.toContain("fixtureProvider")
    expect(scriptSource).not.toContain("task-8-deep-research-real-path")
    expect(scriptSource).not.toContain("deep-research-mock")
    expect(scriptSource).not.toContain('["create", "skill"].join("_")')
    expect(scriptSource).not.toContain('["patch", "skill"].join("_")')
    expect(scriptSource).not.toContain("prompt,")
    expect(scriptSource).not.toContain("finalAssistantText")
    expect(scriptSource).not.toContain("inputPreview")
    expect(scriptSource).not.toContain("textPreview: preview(part.textValue)")
    expect(scriptSource).not.toContain("preview(part.textValue)")
    expect(scriptSource).not.toContain("sanitized.inputPreview")
    expect(scriptSource).not.toContain("data: parseJson(part.dataJson)")
    expect(scriptSource).not.toContain("dataJson: undefined")
    expect(scriptSource).not.toContain("output: toolResult.output")
    expect(scriptSource).not.toContain("fullPromptText: value")
  })
})
