import { describe, expect, test } from "bun:test"
import { readFileSync } from "node:fs"

describe("desktop running states harness", () => {
  test("exposes a dev-only query-param fixture without calling useAgent", () => {
    const appSource = readFileSync("src/desktop/src/App.tsx", "utf8")

    expect(appSource).toContain("shouldShowRunningStatesHarness()")
    expect(appSource).toContain("shouldShowActivityDetailsHarness()")
    expect(appSource).toContain('get("fixture") === "running-states"')
    expect(appSource).toContain('get("fixture") === "activity-details"')
    expect(appSource).toContain("isLocalDesktopDevServer()")
    expect(appSource).toContain('window.location.port === "4173"')
    expect(appSource.indexOf("return <DesktopRunningStatesHarness />")).toBeLessThan(appSource.indexOf("useAgent()"))
    expect(appSource.indexOf("return <DesktopActivityDetailsHarness />")).toBeLessThan(appSource.indexOf("useAgent()"))
  })

  test("keeps each long-running visual state available as a stable scenario", () => {
    const harnessSource = readFileSync("src/desktop/src/DesktopRunningStatesHarness.tsx", "utf8")

    expect(harnessSource).toContain('"thinking"')
    expect(harnessSource).toContain('"reasoning"')
    expect(harnessSource).toContain('"tool"')
    expect(harnessSource).toContain('"permission"')
    expect(harnessSource).toContain('"queued"')
    expect(harnessSource).toContain("activeRun: run")
    expect(harnessSource).toContain("const [language, setLanguage] = useState<DesktopLanguage>(\"zh\")")
    expect(harnessSource).toContain("createRunningFixture(kind, language)")
    expect(harnessSource).toContain("<DesktopTextProvider language={language}>")
    expect(harnessSource).toContain("Switch fixture language to")
    expect(harnessSource).toContain("setLanguage(option)")
    expect(harnessSource).toContain("History message")
    expect(harnessSource).toContain("fixture-completed-browser-call")
    expect(harnessSource).toContain("fixture-completed-shell-call")
    expect(harnessSource).toContain("fixture-completed-read-call")
    expect(harnessSource).toContain("fixture-completed-websearch-call")
    expect(harnessSource).toContain("fixture-completed-skill-call")
    expect(harnessSource).toContain("fixture-completed-agent-call")
    expect(harnessSource).toContain("fixture-running-browser-call")
    expect(harnessSource).toContain("fixture-running-shell-call")
    expect(harnessSource).toContain("fixture-running-read-call")
    expect(harnessSource).toContain("fixture-running-websearch-call")
    expect(harnessSource).toContain("fixture-running-skill-call")
    expect(harnessSource).toContain("fixture-running-agent-call")
    expect(harnessSource).toContain("Activated skill browser")
    expect(harnessSource).toContain("Spawned reviewer subagent")
    expect(harnessSource).toContain("Verified composer and transcript bounds before the live tool step.")
    expect(harnessSource).toContain("Permission composer while the run is suspended.")
    expect(harnessSource).toContain("permissionRequests: kind === \"permission\" ? [createPermissionRequest()] : []")
    expect(harnessSource).toContain("This path is dev-only and does not call the app-server.")
  })

  test("adds a focused activity details fixture for scrolling reasoning and tool details", () => {
    const harnessSource = readFileSync("src/desktop/src/DesktopRunningStatesHarness.tsx", "utf8")

    expect(harnessSource).toContain("export function DesktopActivityDetailsHarness()")
    expect(harnessSource).toContain("?fixture=activity-details")
    expect(harnessSource).toContain("setVisibleLineCount((current) => Math.min(current + 1, reasoningLines.length))")
    expect(harnessSource).toContain("setIsStreaming(false)")
    expect(harnessSource).toContain("createActivityDetailsFixture(language, reasoningLines.slice(0, visibleLineCount).join(\"\\n\"), isStreaming)")
    expect(harnessSource).toContain("activity-completed-shell-call")
    expect(harnessSource).toContain("activity-running-browser-call")
    expect(harnessSource).toContain("LONG_TOOL_OUTPUT_ZH")
    expect(harnessSource).toContain("Replay stream")
  })
})
