import { describe, expect, test } from "bun:test"
import { readFileSync } from "node:fs"

describe("desktop user-path verify script", () => {
  test("exposes a reusable desktop:verify script and keeps the key user-path assertions", () => {
    const packageJson = JSON.parse(readFileSync("package.json", "utf8")) as {
      scripts?: Record<string, string>
    }
    const scriptSource = readFileSync("scripts/desktop-user-path-check.mjs", "utf8")
    const mainSource = readFileSync("src/desktop/electron/main.mjs", "utf8")

    expect(packageJson.scripts?.["desktop:verify"]).toBe("node ./scripts/desktop-user-path-check.mjs")
    expect(scriptSource).toContain("mkdtempSync(join(tmpdir(), \"neo-coworker-desktop-verify-\"))")
    expect(scriptSource).toContain("DESKTOP_SELECTION_STATE_PATH")
    expect(scriptSource).toContain("DESKTOP_SETTINGS_STATE_PATH")
    expect(scriptSource).toContain("NCOWORKER_SERVER_DB_PATH")
    expect(scriptSource).toContain("join(isolatedDesktopStateRoot, \"server.sqlite\")")
    expect(scriptSource).toContain("window.neoCoworkerDesktop.persistedWorkspaceRoot")
    expect(scriptSource).toContain("page.getByRole(\"button\", { name: /Settings|设置/ })")
    expect(scriptSource).toContain("bridge.loadDesktopSettings()")
    expect(scriptSource).toContain("page.getByRole(\"button\", { name: /LLM Settings|LLM 设置/ })")
    expect(scriptSource).toContain("page.getByRole(\"button\", { name: /Apply LLM Settings|应用 LLM 设置/ })")
    expect(scriptSource).toContain("Desktop settings apply did not leave the managed app-server reachable.")
    expect(scriptSource).toContain("page.getByTitle(\"New Session\")")
    expect(scriptSource).toContain("page.locator(\"button[type=submit]\")")
    expect(scriptSource).toContain("matchesExpectedAssistantText")
    expect(scriptSource).toContain("normalizeAssistantText")
    expect(scriptSource).toContain("part.kind === \"text\"")
    expect(scriptSource).toContain("Assistant transcript text is empty.")
    expect(mainSource).toContain("process.env.DESKTOP_SELECTION_STATE_PATH?.trim() ||")
    expect(mainSource).toContain("process.env.DESKTOP_SETTINGS_STATE_PATH?.trim() ||")

    // Task 20: Reasoning controls + Kimi acceptance + evidence artifacts
    expect(scriptSource).toContain("DESKTOP_VERIFY_KIMI")
    expect(scriptSource).toContain("DESKTOP_VERIFY_KIMI_PROVIDER")
    expect(scriptSource).toContain("DESKTOP_VERIFY_KIMI_API_KEY")
    expect(scriptSource).toContain("DESKTOP_VERIFY_KIMI_MODEL")
    expect(scriptSource).toContain("DESKTOP_VERIFY_KIMI_BASE_URL")
    expect(scriptSource).toContain("hasLiveKimiCreds")
    expect(scriptSource).toContain("kimiSubmode")
    expect(scriptSource).toContain("\"live\"")
    expect(scriptSource).toContain("\"fixture\"")
    expect(scriptSource).toContain("startKimiFixtureServer")
    expect(scriptSource).toContain("allocateLoopbackPort")
    expect(scriptSource).toContain("kimi-k2.6")
    expect(scriptSource).toContain("openai-compatible")
    expect(scriptSource).toContain("/v1/chat/completions")
    expect(scriptSource).toContain("/v1/models")
    expect(scriptSource).toContain("task-20-kimi-acceptance.json")
    expect(scriptSource).toContain("kimiAcceptanceJsonPath")
    expect(scriptSource).toContain("fixtureProviderRequests")
    expect(scriptSource).toContain("DESKTOP_VERIFY_REASONING_EFFORT")
    expect(scriptSource).toContain("DESKTOP_VERIFY_THINKING_ENABLED")
    expect(scriptSource).toContain("driveReasoningControls")
    expect(scriptSource).toContain("locateLabeledTrigger")
    expect(scriptSource).toContain("Enable thinking|启用思考")
    expect(scriptSource).toContain("Reasoning effort|推理强度")
    expect(scriptSource).toContain("button[aria-haspopup=\\\"listbox\\\"]")
    expect(scriptSource).toContain("Reasoning thinking control did not persist")
    expect(scriptSource).toContain("Reasoning effort control did not persist")
    expect(scriptSource).toContain("editLlmFields")
    expect(scriptSource).toContain("chooseProvider")
    expect(scriptSource).toContain("fillFieldByLabel")
    expect(scriptSource).toContain("assertPersistedLlmField")
    expect(scriptSource).toContain("LLM provider|LLM 提供商")
    expect(scriptSource).toContain("API key|API Key")
    expect(scriptSource).toContain("Model|模型")
    expect(scriptSource).toContain("Base URL")
    expect(scriptSource).toContain(".sisyphus")
    expect(scriptSource).toContain("evidenceJsonPath")
    expect(scriptSource).toContain("evidenceScreenshotPath")
    expect(scriptSource).toContain("evidenceReasoningScreenshotPath")
    expect(scriptSource).toContain("evidenceTracePath")
    expect(scriptSource).toContain("traceContext.tracing.start")
    expect(scriptSource).toContain("traceContext.tracing.stop")
    expect(scriptSource).toContain("page.screenshot({ path: evidenceScreenshotPath, fullPage: true })")
    expect(scriptSource).toContain("page.screenshot({ path: evidenceReasoningScreenshotPath, fullPage: true })")

    // Task 21: telemetry/sqlite evidence extraction from the real desktop flow
    expect(scriptSource).toContain("task-21-telemetry-success.txt")
    expect(scriptSource).toContain("task-21-telemetry-sources.txt")
    expect(scriptSource).toContain("task21EvidenceJsonPath")
    expect(scriptSource).toContain("/runs/${encodeURIComponent(latestRunId)}/trace")
    expect(scriptSource).toContain("readTask21SqliteEvidence")
    expect(scriptSource).toContain("spawnSync(\"python\"")
    expect(scriptSource).toContain("SELECT sequence, source, event_type, data_json FROM run_event")
    expect(scriptSource).toContain("SELECT message_id, kind, text_value FROM part")
    expect(scriptSource).toContain("assistantReasoningReplayMessageCount")
    expect(scriptSource).toContain("validateKimiReplayRequest")
    expect(scriptSource).toContain("reasoning_content is missing")
    expect(scriptSource).toContain("capability.resolution.recorded")
    expect(scriptSource).toContain("context.window.resolved")
    expect(scriptSource).toContain("kimi.run.classified")
  })
})
